---
title: "Binomial Distribution"
author: "Ajay Karthick"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Coin flip simulation

```{r coin_flip_simulation}
coin <- c('head', 'tail')
num_flips <- 2
flips <- sample(coin, size = num_flips, replace = TRUE, prob = c(0.6, 0.4))
table(flips)
```

### prevent R from displaying numbers in scientific notation 
```{r prevent_sci_notation}
options(scipen=999)
```

### rbinom

```{r rbinom}
num_of_observations <- 100
results <- rbinom(num_of_observations, 2, 0.5)
table(results) / num_of_observations
```


### dbinom
```{r}
success <- 0:num_of_observations
pmf <- dbinom(x=success, size=num_of_observations, prob=0.5)
plot(success, 
     pmf,
     type='h',
     main='Binomial Distribution - PMF',
     xlab='# Success',
     ylab='Probability',
     lwd=3)
```

### pbinom
```{r}
#pbinom(q=1, size=2, prob=0.5, lower.tail = FALSE)
cdf <- pbinom(q=success, size=num_of_observations, prob=0.5)
plot(success, 
     cdf,
     type='h',
     main='Binomial Distribution - CDF',
     xlab='# Success',
     ylab='Probability',
     lwd=3)

```



## qbinom
```{r}
quantiles <- seq(0, 1, .001)
inverse_cdf <- qbinom(p=quantiles, size=num_of_observations, prob=0.5)
plot(quantiles, 
     inverse_cdf,
     type='s',
     main='Binomial Distribution - Quantile',
     xlab='p',
     ylab='Q(p)',
     lwd=1)
```


In a large population of adults, 70% have received CPR training. If 40 adults from this population are selected randomly, what is the probability that the 30 adults out of 40 have received the CPR training?

```{r}
p = 0.7
n = 40
k = 30
```

\[
P[X=k] = {n \choose k} p^k (1-p)^{(n-k)}
\]
\[ 
P[X=30] = {40 \choose 30} * 0.7^{30}* 0.3^{10}\\
= 0.1128173
\]


